language: cpp

before_install:
  - export -f travis_fold
  - third-party/qt_installer/qt_installer.sh

install:
  # QtFtp
  - pushd third-party/qtftp
  - qmake CONFIG+=staticlib CONFIG+=c++11 CONFIG+=release
  - make
  - popd

  # QuaZIP
  - pushd third-party/quazip
  - qmake CONFIG+=staticlib CONFIG+=c++11 CONFIG+=release LIBS+=-lz
  - make
  - popd

  # Fotorelacjonusz
  - ci/write_secrets_h.sh
  - lrelease fotorelacjonusz.pro
  - qmake CONFIG+=release
  - make

script:
  - ${EXE} -v

before_deploy:
  - macdeployqt Fotorelacjonusz.app -verbose=2
  - tar czf Fotorelacjonusz-nightly-macos.tar.gz Fotorelacjonusz.app

deploy:
  provider: bintray
  file: "ci/bintray_nightly.json"
  user: "skalee"
  key:
    secure: NLhO90y/IC0XOnj19U5ZZleKhfs7bo1KCXQgRz1W6Vr9q2DRVFdcnNrdcVpnNagwbvrFFqmG1SHDnuZwTAnq1WUlMXTVEE+XfuBINc0soKdr9gy48Qryhrx8cixrEeQE4JTJQ+J1wOvNN9qVzgj3XqAguD+WyU/LPKAbm/iXmyhzlrAE++MyvXJi3tTc0tgtA9Ek/UHVriZPdwMktIR8SZ4THHUwi/tkn1Yxr94gICH/sKmOUi+po2XO3q+xorabXw+tn+5t58HyD0L+6QUfkY0WZLvwWaEM5+tel4Ltp5Bg5oMUZeD36J3TKptksLUmYQpbUkNI17fzeq/hJHbX5G+1gK0Ch+Khre91Ol0YZv0BVAB74aqgvfDxyUT4cFE2o82x7zQetzVAMNN2Njj6VNVlXlFoQqPzWl6XzATi/p0yb6ZkQXkvXjQ+3JF67XvAXWakyjqf8h0K6cgRSgAXBl9NXCn9p0TF8p8ZYC9N0pUYIrVS6v7T7QmZeSg1Czav2rQQgw7Z36/nOtxVKUzVgLPRZZC8nLCCH9FPbmAsYV2j9d8j0oQwH+FcAXzPV925s5e23r9RnAgeF8cprrJB9GvGdWEgA06StHEvYXbAzG6oP78IfXb+uenicVoCaxmfEg/qucVCCwg5XiA+JFMJUFHybRoyAGz4az7+Dwfij+s=
  skip_cleanup: true # to upload artifacts created during the build
  on:
    repo: skalee/fotorelacjonusz
    branch: master

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env:
        - EXE=./Fotorelacjonusz.app/Contents/MacOS/Fotorelacjonusz
        - PATH="/opt/Qt/5.12.3/clang_64/bin:${PATH}"
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-mac-x64-online.dmg"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/qt_installer_vars_mac.js"
