language: cpp

before_install:
  - export -f travis_fold
  - if [[ $INSTALL_QT = yes ]]; then third-party/qt_installer/qt_installer.sh; fi

install:
  - ci/write_secrets_h.sh
  - ci/build_on_${TRAVIS_OS_NAME}.sh

script:
  - ci/run_checks.sh

before_deploy:
  # Set TRAVIS_TAG to "nightly" if blank (i.e. triggered by push to master).
  - export TRAVIS_TAG=${TRAVIS_TAG:-nightly}
  - git tag -a -f -m "Created by Travis" $TRAVIS_TAG
  - ci/package.sh

deploy:
  provider: releases
  file_glob: true
  file: release/*
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: Pl1eq4L1Na7+2e9c3zEK3RG1a+CLR4b68k0ye2zl5h8z7wVVPPsn0FrfPvZZWk48jgI9HXDhR0zzctV1dh1ykZmowIZJZsBUguhlaIlyWsCSuCf1uIBXQG8naWu3AjJxefz8/KYF6aOJACU4sZFviW1e2vMtKF+Q6BXrjEhLQlc0pflTwBxOnlq2fTmt0uP9UuSP62Py0XbbaybAJAMEfSDb4lAZ5bwVXmOvCREP+vnSTlj/uiPxmw74jxYAmhX6kzgwN0i8XOwEjMSDmjtDyvr8dNN52GKDzpEt2R2UP8Z4ybYM7blyYj97GBi2ICPIh/IIE++R9qsMUDeR8OT28CVvrqd92cFZlNMC8YvTl4fvhzqJirWecGWqdCuhgSinMIIoplhqv48rtLtvrXHlNTSzFiElKodU2hbQrAjqZmFpugco21A3MreDt7BwL5HJvtr86bANpIqYuCOQNkpoNTpX1+4w6wwRAMv4Z5bhVbwkJK6Z8p3tJNBl9kBxfU5/YssOzY/x1pO9Ya14G6T0+YlH1+TNivPbfEPdNsSwXKKnH2A/CHZylQo0asmZV7ckDW3kAO2AASiYA3svi1IFMJUPASd01sQLwEGsZTTN8J6FKL9NauKd5QFtATTTOHRi0trARRak4L7lPI7E0LoGfzjOmIJn8dm43f+nMp4a8vU=
  on:
    repo: skalee/fotorelacjonusz
    all_branches: true
    condition: ("x${TRAVIS_TAG}" != "x") || ("${TRAVIS_BRANCH}" = master)

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env:
        - INSTALL_QT=yes
        - PATH="/opt/Qt/5.12.3/clang_64/bin:${PATH}"
        - QT_INSTALLER_DOWNLOAD_NAME="qt-unified-mac-x64-online.dmg"
        - QT_INSTALLER_VARS="${TRAVIS_BUILD_DIR}/ci/qt_installer_vars_mac.js"
